spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  # jpa 관련 설정
  jpa:
    hibernate:
      # create: 테이블을 만들려고 하는데, 이미 있으면 제거(DROP)하고 다시 만든다,
      # create-drop
      # update: DDL과 실제 데이터베이스 테이블이 다를 경우 수정
      # none: DDL을 전혀 사용하지 않는다.
      ddl-auto: create
    # 실제로 실행되는 SQL을 출력하고 싶을 때
    show-sql: true
    # 내가 사용하는 데이터베이스의 방언
    database-platform: org.hibernate.community.dialect.SQLiteDialect

    # 여기 아래는 초기 데이터 용 설정
    defer-datasource-initialization: true
  sql:
    init:
      mode: always